student = {
	firstName: 'nholuong',
	lastName: 'Luong',
	email: 'test@example.com',
	gender: 'F',
	country: 'Vietnam',
	isStudentActive: false,
	favouriteSubjects: ['maths', 'english', 'cs'],
	totalSpentInBooks: 0.0,
};

students = [
	{
		firstName: 'nholuong1',
		lastName: 'Luong',
		email: 'test1@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'nholuong2',
		lastName: 'Luong',
		email: 'test2@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'nholuong3',
		lastName: 'Luong',
		email: 'test1@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'nholuong3',
		lastName: 'Luong',
		email: 'test3@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'nholuong4',
		lastName: 'Luong',
		email: 'test4@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'nholuong5',
		lastName: 'Luong',
		email: 'test5@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'nholuong6',
		lastName: 'Luong',
		email: 'test6@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'nholuong7',
		lastName: 'Luong',
		email: 'test7@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'nholuong8',
		lastName: 'Luong',
		email: 'test8@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'nholuong9',
		lastName: 'Luong',
		email: 'test9@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
	{
		firstName: 'nholuong10',
		lastName: 'Luong',
		email: 'test10@example.com',
		gender: 'F',
		country: 'Vietnam',
		isStudentActive: false,
		favouriteSubjects: ['maths', 'english', 'cs'],
		totalSpentInBooks: 0.0,
	},
];
